### ISSUE TITLE
太极magisk

### ISSUE THREAD

**Issue by miomiola** [cinit/QNotified#1]
模块显示激活
`SystemClassLoader: dalvik. system. PathClassLoader[ DexPathList[[ directory"."], nativeLibraryDirectories=[/ system/lib64,/ system/ vendor/lib64,/ system/lib64,/ system/ vendor/lib64]]] ActiveModuleVersion:1 ThisVersion:1`
但是QQ内未生效

**Comment by cinit** [comment]
请问您的插件版本是0.1.6, QQ版本是8.1.0 ,安卓版本?

**Comment by cinit** [comment]
不好意思...按错了,在root下执行
logcat -v time -s XposedStartupMarker:D Xposed:I appproc:I DexposedBridge:I art:F >> /sdcard/error.log
可以获取日志，能一起带上日志吗？(抓取日志的时候复现问题,就是再操作一次)

**Comment by miomiola** [comment]
插件0.1.2 QQ 8.0.8 安卓9

**Comment by cinit** [comment]
你更新一下插件，好吗？release里有0.1.6,太极审核通过的,试试那个

**Comment by miomiola** [comment]
成功了 !.
