### ISSUE TITLE
TIM 3.0.0在更新0.8.3以后出现消息列表已经聊天界面头像消失的情况

### ISSUE THREAD

**Issue by luoquan-30** [cinit/QNotified#100]
![19acd47b9a7e8a66](https://user-images.githubusercontent.com/62764563/87808563-8163cf00-c88c-11ea-9755-c7a102bcc2f6.jpg)
就是图片上这样

**Comment by charmless24** [comment]
我也是这样，一点头像就闪退了

**Comment by cinit** [comment]
0.8.0的时候还没有问题对吧?

**Comment by luoquan-30** [comment]
> 0.8.0的时候还没有问题对吧?

是的，0.8.0的时候是正常的

**Comment by cinit** [comment]
已在[d9c728f](https://github.com/cinit/QNotified/commit/d9c728f941d31c8df3e00b81a0b814b99a4b44d7)中修复, 请测试

**Comment by luoquan-30** [comment]
> 已在[d9c728f](https://github.com/cinit/QNotified/commit/d9c728f941d31c8df3e00b81a0b814b99a4b44d7)中[修复](https://github.com/cinit/QNotified/commit/d9c728f941d31c8df3e00b81a0b814b99a4b44d7)，请测试

那啥，我直接CI构建下载就可以了吧？

**Comment by cinit** [comment]
@luoquan-30 是的

**Comment by luoquan-30** [comment]
> @luoquan-30 是的

我刚刚下载看了一下，是e8d1e84的版本诶，这个咋搞

**Comment by cinit** [comment]
@luoquan-30 e8d1e84版本头像能正常加载吗？

**Comment by luoquan-30** [comment]
> 已在[d9c728f](https://github.com/cinit/QNotified/commit/d9c728f941d31c8df3e00b81a0b814b99a4b44d7)中[修复](https://github.com/cinit/QNotified/commit/d9c728f941d31c8df3e00b81a0b814b99a4b44d7)，请测试

我刚刚才看明白，下载的版本应该是的，但是好像还是没有修复，我这里还是没有显示头像

**Comment by cinit** [comment]
@luoquan-30 重启试试?

**Comment by luoquan-30** [comment]
> @ luoquan-30 e8d1e84版本头像能正常加载吗？

最开始是不行的，然后好像我在设置花Q里面开启了关闭截屏分享，进行了重新混淆以后，就可以了，不是很确定是不是这个原因，因为中途，TIM出现了一次闪退，但是目前已经可以正常使用了，感谢(*^_^*)

**Comment by luoquan-30** [comment]
> 已在[d9c728f](https://github.com/cinit/QNotified/commit/d9c728f941d31c8df3e00b81a0b814b99a4b44d7)中修复, 请测试

我这边又出现问题了，但是我不知道是不是你删了，就是卡片代码和群发文字消息不见了，这是bug还是被删除了啊？我已经通过高级验证了

**Comment by cinit** [comment]
卡片和群发文字这两个功能废除了

**Comment by luoquan-30** [comment]
> 卡片和群发文字这两个功能废除了

这样啊，是出于安全方面的考虑嘛😂卡片还是挺好玩的，其实蛮想要回来的

**Comment by cinit** [comment]
主要是卡片消息频繁被用于引流，群发文本消息常被用于代发广告，两个功能充斥着金钱的恶臭


 
---原始邮件---
发件人: "luoquan-30"<notifications@github.com&gt;
发送时间: 2020年7月27日(星期一) 凌晨0:25
收件人: "cinit/QNotified"<QNotified@noreply.github.com&gt;;
抄送: "cinit"<1041703712@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [cinit/QNotified] TIM 3.0.0在更新0.8.3以后出现消息列表已经聊天界面头像消失的情况 (#100)




  
卡片和群发文字这两个功能废除了
  
这样啊，是出于安全方面的考虑嘛😂卡片还是挺好玩的，其实蛮想要回来的

**Comment by luoquan-30** [comment]
> 主要是卡片消息频繁被用于引流，群发文本消息常被用于代发广告，两个功能充斥着金钱的恶臭
> […](#)
> ---原始邮件--- 发件人: "luoquan-30"<notifications@github.com&gt; 发送时间: 2020年7月27日(星期一) 凌晨0:25 收件人: "cinit/QNotified"<QNotified@noreply.github.com&gt;; 抄送: "cinit"<1041703712@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [cinit/QNotified] TIM 3.0.0在更新0.8.3以后出现消息列表已经聊天界面头像消失的情况 (#100) 卡片和群发文字这两个功能废除了 这样啊，是出于安全方面的考虑嘛卡片还是挺好玩的，其实蛮想要回来的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

原来是这样啊，很抱歉<(_ _)>，我不是很了解黑产这方面的，既然是这样的话，那我支持你的选择😂功能被恶意使用确实很糟心，但是历史版本的还是可以继续使用吧，有没有办法进行限制

**Comment by cinit** [comment]
@luoquan-30 对，历史版本可以继续用，但是历史版本在兼容性方面出各种问题是迟早的事

**Comment by luoquan-30** [comment]
> @luoquan-30 对，历史版本可以继续用，但是历史版本在兼容性方面出各种问题是迟早的事

哈哈哈哈哈，可以可以
