### ISSUE TITLE
华和狐狸看这里

### ISSUE THREAD

**Issue by MMMXDyyy** [cinit/QNotified#109]
qq版本8.4.1  模块版本0.8.3.398c0db
虽然和华反馈了但还想来github反馈一下
diy名片失效

**Comment by cinit** [comment]
快了快了, 在做了

**Comment by MMMXDyyy** [comment]
啊这（滑稽）

**Comment by cinit** [comment]
8.4.1 CI版本现在能用了吗?

**Comment by MMMXDyyy** [comment]
可以了，就是有时候白屏
------&nbsp;原始邮件&nbsp;------
发件人:&quot;cinit&quot;<notifications@github.com&gt;;
发送时间:2020年7月27日(星期一)&nbsp;凌晨0:09
收件人:&quot;cinit/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送人:&quot;MMMXDyyy&quot;<2963352337@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:Re:&nbsp;[cinit/QNotified]&nbsp;华和狐狸看这里&nbsp;(#109)



 
8.4.1 CI版本现在能用了吗?
 
&mdash;
