### ISSUE TITLE
TIM3.1.0.2878模块失效

### ISSUE THREAD

**Issue by excited233** [cinit/QNotified#115]

**Comment by cinit** [comment]
TIM3.1.0.2878哪里下载?

**Comment by cinit** [comment]
是模块完全失效(无法加载)吗? 还是部分功能无法使用?

**Comment by excited233** [comment]
模块完全失效，无法使用。
最近出的测试，QQ换皮精简版，链接如下
取件链接：https://c-t.work/s/8a93e346935345 或使用取件码：jhkcqe。复制整段文案打开奶牛快传App，获取分享内容更快速哦。
希望能尽快修复🙏


 
---原始邮件---
发件人: "cinit"<notifications@github.com&gt;
发送时间: 2020年7月26日 22:50:24
收件人: "cinit/QNotified"<QNotified@noreply.github.com&gt;;
抄送: "Too_young"<1262340874@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [cinit/QNotified] TIM3.1.0.2878模块失效 (#115)




 
是模块完全失效(无法加载)吗? 还是部分功能无法使用?

**Comment by cinit** [comment]
似乎只是入口消失, 在[62e1603](https://github.com/cinit/QNotified/commit/62e16032ffc585460f4262f69b537beddc40150d)修复, 请测试

**Comment by excited233** [comment]
能用了，我一开始清除了数据，误以为完全失效😅


 
---原始邮件---
发件人: "cinit"<notifications@github.com&gt;
发送时间: 2020年7月26日 23:50:08
收件人: "cinit/QNotified"<QNotified@noreply.github.com&gt;;
抄送: "Too_young"<1262340874@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [cinit/QNotified] TIM3.1.0.2878模块失效 (#115)




 
似乎只是入口消失, 在62e1603修复, 请测试
