### ISSUE TITLE
0.4.1界面错位

### ISSUE THREAD

**Issue by HinataKato** [cinit/QNotified#12]
![Screenshot_2019-12-19-05-29-10-350_com tencent mobileqq](https://user-images.githubusercontent.com/57648531/71124857-b9386480-2220-11ea-8198-be9b24729b08.jpg)
很久之前更新就这样了，懒癌发作现在才发issue

**Comment by cinit** [comment]
哪里错位了?

**Comment by HinataKato** [comment]
> 哪里错位了?

文字

**Comment by HinataKato** [comment]
> > 哪里错位了?
> 
> 文字

啊我傻了，我还以为跟上面是连着的
