### ISSUE TITLE
miui12使用edxp后台有条报错信息一直在报错

### ISSUE THREAD

**Issue by wuzhongwu** [cinit/QNotified#123]
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: java.lang.NullPointerException: obj/class == null
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.hasField(Utils.java:1213)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.hasField(Utils.java:1209)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.getApplication(Utils.java:97)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.config.ConfigManager.getDefaultConfig(ConfigManager.java:57)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook.deleteDirIfNecessary(StartupHook.java:111)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook.access$100(StartupHook.java:42)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook$2.beforeHookedMethod(StartupHook.java:104)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:94)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.Application.attach(Unknown Source:0)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.Instrumentation.newApplication(Unknown Source:12)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.LoadedApk.makeApplication(Unknown Source:60)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(Unknown Source:1205)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread.access$1400(Unknown Source:0)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.os.Looper.loop(Unknown Source:251)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread.main(Unknown Source:98)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
07-28 16:48:32.120 21663 21663 I EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: java.lang.AssertionError: FATAL: Utils.getApplication() failure!
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.getApplication(Utils.java:103)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.config.ConfigManager.getDefaultConfig(ConfigManager.java:57)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook.deleteDirIfNecessary(StartupHook.java:111)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook.access$100(StartupHook.java:42)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook$2.beforeHookedMethod(StartupHook.java:104)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:94)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.Application.attach(Unknown Source:0)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.Instrumentation.newApplication(Unknown Source:12)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.LoadedApk.makeApplication(Unknown Source:60)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(Unknown Source:1205)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread.access$1400(Unknown Source:0)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.os.Looper.loop(Unknown Source:251)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at android.app.ActivityThread.main(Unknown Source:98)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: Caused by: java.lang.NullPointerException: obj/class == null
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.hasField(Utils.java:1213)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.hasField(Utils.java:1209)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	at nil.nadph.qnotified.util.Utils.getApplication(Utils.java:97)
07-28 16:48:32.121 21663 21663 I EdXposed-Bridge: 	... 19 more
07-28 16:48:32.213 21663 21663 I EdXposed-Bridge: getAppRuntime/W invoked but not in main process!
07-28 16:48:32.213 21663 21663 I EdXposed-Bridge: getLongAccountUin/E getAppRuntime == null
07-28 16:48:32.213 21663 21663 I EdXposed-Bridge: getAppRuntime/W invoked but not in main process!
07-28 16:48:32.214 21663 21663 I EdXposed-Bridge: getLongAccountUin/E getAppRuntime == null
07-28 16:48:32.214 21663 21663 I EdXposed-Bridge: getAppRuntime/W invoked but not in main process!
07-28 16:48:32.214 21663 21663 I EdXposed-Bridge: getLongAccountUin/E getAppRuntime == null

**Comment by cinit** [comment]
这个问题现在master分支好像已经修复了

**Comment by wuzhongwu** [comment]
当前版本是0.8.3，master我看他tag最新的也是0.8.3，当前已经发布的版本还没有修复是吧

**Comment by cinit** [comment]
是的

**Comment by wuzhongwu** [comment]
好的，感谢，等下下一个版本
