### ISSUE TITLE
简洁模式圆头像导致状态栏变色失效

### ISSUE THREAD

**Issue by Robotxm** [cinit/QNotified#132]
感觉 QN 和花 Q 在实现简洁模式圆头像的方式好像不太一样？QN 开启圆头像之后会导致状态栏不能正常变色，花 Q 就不会

**Comment by cinit** [comment]
抄的花q老版本啊...我没看新版

**Comment by Robotxm** [comment]
我看花 Q 里 Hook 的方法设置的值类型是 byte，和 QN 设置的 bool 不一样。可以的话不知道能不能后面更新一下？

**Comment by singleNeuron** [comment]
新版抄完了
