### ISSUE TITLE
无法启用模块

### ISSUE THREAD

**Issue by moshangsama** [cinit/QNotified#144]
太极中选择启用了模块，可QQ中没反应
![Screenshot_20200807_154100_com tencent mobileqq](https://user-images.githubusercontent.com/53032476/89625098-dc0bac00-d8c9-11ea-9801-448ab7cdceb6.jpg)
![Screenshot_20200807_154052_me weishu exp](https://user-images.githubusercontent.com/53032476/89625109-df069c80-d8c9-11ea-80d2-ba03e75f59a4.jpg)

**Comment by jk1614016** [comment]
目测你用的太极，貌似太极没有适配这个版本
