### ISSUE TITLE
太极突然无法支持

### ISSUE THREAD

**Issue by jinyunkai** [cinit/QNotified#146]
昨天用的好好的，不知道什么时候开始太极就无法生效了，QQ无法找到入口，而且太极显示支持范围是逍遥的版本...我直接懵逼

**Comment by shallmw** [comment]
我也遇到了这个问题

**Comment by taycke** [comment]
因为之前的版本存在极大的倒卖/恶意问题，所以我们在太极取消适配了。

**Comment by shallmw** [comment]
> 因为之前的版本存在极大的倒卖/恶意问题，所以我们在太极取消适配了。

无法刷xposed用户暴风哭泣

**Comment by taycke** [comment]
@shallmw 太极用户可以下载最新版

**Comment by LovKee** [comment]
下载太极6.3版本还是无法支持，手机华为mete10，版本安卓10

**Comment by molan666** [comment]
> @shallmw 太极用户可以下载最新版

最新版是0.8.3吗  不管用，还是哪里的最新版，能给个链接吗大佬

**Comment by taycke** [comment]
@molan666 https://taycke.lanzous.com/b00zlv3zg

**Comment by LovKee** [comment]
@taycke 有没有能发图片红包的版本

**Comment by taycke** [comment]
@LovKee 图片红包是什么？

**Comment by LovKee** [comment]
@taycke XML代码的

**Comment by taycke** [comment]
@LovKee 支持的版本，我们都下架了。

**Comment by LovKee** [comment]
@taycke 大佬，太狠了

**Comment by vahkx1113** [comment]
> @molan666 https://taycke.lanzous.com/b00zlv3zg

为啥我这个显示无法安装？我把旧版本卸载了也无法安装，一加5安卓10
![Screenshot_20200817-103908](https://user-images.githubusercontent.com/65434957/90352677-9d6ab400-e076-11ea-8d9e-bc38db4648c8.jpg)
