### ISSUE TITLE
自定义机型无法去除颜色

### ISSUE THREAD

**Issue by Mubai-Dust** [cinit/QNotified#161]
手机型号：MI 5S
系统：Android 10
Xposed版本：太极阳6.3.0
QQ版本：8.4.1
QN版本：0.8.7.27.24ed155
在自定义机型且重启后
机型可以正常改变
但似乎无法去除机型后的颜色
请问是否原本就是这样设计的呢？

**Comment by taycke** [comment]
@Mubai-Dust 这是个bug，已记录

**Comment by Mubai-Dust** [comment]
> @Mubai-Dust 这是个bug，已记录

好的 十分感谢

**Comment by cinit** [comment]
因该是TX检测到你们搞事情故意为难你们

**Comment by MessCode994** [comment]
@cinit rikka特性
