### ISSUE TITLE
更新到最新版本后刷新功能消失

### ISSUE THREAD

**Issue by WeiEAL** [cinit/QNotified#17]
把隐藏小程序关掉之后就正常了，一开这个功能连刷新都没了
好像QQ上个版本没这个问题，最新版有

**Comment by cinit** [comment]
有没有试过 QNotified设置-故障排查-重置模块?

**Comment by WeiEAL** [comment]
> 有没有试过 QNotified设置-故障排查-重置模块?

用了之后好像能刷新了，只是松开的时候才会显示刷新，谢谢

**Comment by mylovesaber** [comment]
> 有没有试过 QNotified设置-故障排查-重置模块?

qq版本8.2.6,
模块版本0.5.2
关闭所有选项后重置模块设置，之后后台划掉qq，重开，进qq下拉第一段刷新，第二段进入小程序，
打开屏蔽小程序后重开qq，进qq下拉第一段松手提示刷新，再往下滑不松手直接进入小程序，
屏蔽失败

**Comment by cinit** [comment]
这个问题春节活动鼓力全开结束以后还存在吗？

**Comment by mylovesaber** [comment]
> 这个问题春节活动鼓力全开结束以后还存在吗？

似乎不存在了，我也重置过测试了
