### ISSUE TITLE
小尾巴的一些问题

### ISSUE THREAD

**Issue by poly000** [cinit/QNotified#170]
@lliioollcn 
QQ版本： 8.4.5
1. _启用小尾巴时无法回复_
3. _希望支持使用时间 日期 电量 设备型号 系统版本等等_
4. 小尾巴对+1无效（选择开关？）

**Comment by singleNeuron** [comment]
@poly000 直接加个正则替换算了

**Comment by taycke** [comment]
@poly000 干脆直接删除算了

**Comment by poly000** [comment]
已经全部完成且未提交
