### ISSUE TITLE
模块功能求助

### ISSUE THREAD

**Issue by pkuislm** [cinit/QNotified#171]
新版没有xml消息的功能开关了，是被移除了吗？如果是被移除了，我想知道最后一版支持这个功能的版本

**Comment by cinit** [comment]
没移除, 只是临时隐藏了, 代码里仍然存在

**Comment by poly000** [comment]
在Alpha

**Comment by singleNeuron** [comment]
@pkuislm 399解锁白名单

**Comment by pkuislm** [comment]
> @pkuislm 399解锁白名单

没有理解意思，白名单是什么

**Comment by singleNeuron** [comment]
@pkuislm 399CNY，付费解锁

**Comment by cinit** [comment]
建议自己用AS修改然后build, 就有卡片了

**Comment by pkuislm** [comment]
> 建议自己用AS修改然后build, 就有卡片了

好的，感谢
