### ISSUE TITLE
自己构建的没有效果

### ISSUE THREAD

**Issue by nkxingxh** [cinit/QNotified#180]
我fork了一份代码，并且在AppCenter进行构建，可以成功构建，但是构建出来的没有用（在QQ设置中没有QNotified设置），请问怎么解决，谢谢

**Comment by cinit** [comment]
太极?

**Comment by nkxingxh** [comment]
是的，太极阴

**Comment by cinit** [comment]
@nkxingxh 太极阴 会对模块进行签名校验，请换 无极/edxp/应用转生 之类没有模块限制的框架

**Comment by nkxingxh** [comment]
好的，谢谢
