### ISSUE TITLE
小尾巴的问题

### ISSUE THREAD

**Issue by poly000** [cinit/QNotified#189]
FR:
1. <del>加入临时开关（长按某个按钮）以应对特殊情况（左下角语音？）</del>
2. <del>加入便捷关键词输入 手动打#xxxx#太麻烦了</del>

BR:
1. <del>电量显示的是QN设置的电量 即使我并没有使用“自定义电量”功能</del>

@lliioollcn

**Comment by cinit** [comment]
@cinit 然后就和检查消息冲突了

**Comment by poly000** [comment]
左下角还有个语音（

**Comment by lliioollcn** [comment]
显示的是QN的电量的话，你重启下就好了吧。。。
他是实时判断QN假电量功能是否开启，如果一直返回开启那就会一直显示QN的假电量
1、在下个版本，如果输入的不是卡片代码，那么长按发送将会携带小尾巴（前提是你已经通过了高级验证）
2、便捷关键词输入将会在下个版本加入
