### ISSUE TITLE
太极阴环境下出现阻止QQ闪退的toast

### ISSUE THREAD

**Issue by zhanghua000** [cinit/QNotified#22]
QQ版本：8.1.5
QNotified版本：0.5.2
操作：尝试打开发送卡片消息的开关
截图：
https://sm.ms/image/ohpRECjYLqGD7dX

**Comment by cinit** [comment]
先更新到0.6.0-rc2

**Comment by zhanghua000** [comment]
已解决，谢谢作者大大

**Comment by zhanghua000** [comment]
更新了，现在不会产生toast了，但是发送xml卡片时有新的情况：
https://sm.ms/image/tSuiHIbBA9EnKWr

**Comment by cinit** [comment]
看一下log，应该会有记录的

**Comment by cinit** [comment]
我怀疑还是无法定位到混淆类惹的事

**Comment by zhanghua000** [comment]
log是这个截图里面的内容吗@cinit 

![Screenshot_20200205_100031_com.tencent.mobileqq.jpg](https://i.loli.net/2020/02/05/WbwLIB8T9tuUqDZ.jpg)

**Comment by cinit** [comment]
当然是Xposed/EdXp的模块(详细)日志

**Comment by zhanghua000** [comment]
可是太极阴环境下没有找到查看模块日志的入口。

**Comment by cinit** [comment]
太极就这个样子，没办法

**Comment by zhanghua000** [comment]
赞美大佬，0.7.1beta现在看起来已经没问题了
