### ISSUE TITLE
[Bug]TIM 3.1.1 复读，花Q，QQ净化异常

### ISSUE THREAD

**Issue by bluboy-official** [cinit/QNotified#266]
版本0.8.9.140
目前测试出来如下bug
+1标志因为消息较长而歪掉并且标志变小
触发了QQ自己的复读机制时出现两个加一（有的时候不触发也会莫名有两个加一 不过这种情况较少）
点击加一的时候复读的不是你点击加一位置的那条消息，往往是之前同一个人的发言
花q不能显示具体消息数量，模块重置多次都显示初始化失败
qq净化中 以图片打开闪照同样初始化失败
以上，感谢大佬维护，希望能尽快修复bug

**Comment by taycke** [comment]
@bluboy-official QQ版本多少

**Comment by taycke** [comment]
@bluboy-official +1变小那是QQ的锅
点击+1复读那个是你的问题吧（除了你没人有这种bug）
花Q显示具体消息数量啊
QQ净化里面初始化失败应该是你的手机/QQ问题

**Comment by taycke** [comment]
@bluboy-official Tim3.1.1还没进行适配（开学了开发都没啥睡觉了）

**Comment by bluboy-official** [comment]
啊这 那需要我到时候去telegram给你们提供更多的信息吗（
