### ISSUE TITLE
为什么删除了发送xml卡片信息的功能

### ISSUE THREAD

**Issue by tianqiqaq** [cinit/QNotified#277]
此功能之前一直使用着，但是从某一版本开始此功能没有了，询问一下为何删除了？我这里没有找到此功能，是新版本改位置了吗？

**Comment by singleNeuron** [comment]
此功能被滥用

**Comment by 122cygf** [comment]
![IMG_20200906_224443](https://user-images.githubusercontent.com/55302758/92328320-9beb4500-f092-11ea-8b20-db259c2f24b5.jpg)

**Comment by singleNeuron** [comment]
@tianqiqaq 目前开发组正在商讨逐步开放卡片白名单，请期待后续更新

**Comment by tianqiqaq** [comment]
> @tianqiqaq 目前开发组正在商讨逐步开放卡片白名单，请期待后续更新

好的，谢谢，因为本人是开发者，所以这个功能还是比较常用的，真心希望尽快重新添加，麻烦了

**Comment by singleNeuron** [comment]
@tianqiqaq 开发啥的？有合理理由且保证不滥用的话可以考虑给授权

**Comment by 122cygf** [comment]
有开发能力的话可以自己拉代码改一改，编一个自用的

**Comment by tianqiqaq** [comment]
> @tianqiqaq 开发啥的？有合理理由且保证不滥用的话可以考虑给授权

就是我开了个我的世界服务器，然后写了个配套的机器人，然后用此功能（复制代码）主要是为了方便开发，然后就是说复制代码应该不会造成滥用吧，我觉得可以把复制代码功能恢复一下awa

**Comment by tianqiqaq** [comment]
> 有开发能力的话可以自己拉代码改一改，编一个自用的

emm目前不会开发xp插件，我可以试试

**Comment by singleNeuron** [comment]
> > @tianqiqaq 开发啥的？有合理理由且保证不滥用的话可以考虑给授权
> 
> 就是我开了个我的世界服务器，然后写了个配套的机器人，然后用此功能（复制代码）主要是为了方便开发，然后就是说复制代码应该不会造成滥用吧，我觉得可以把复制代码功能恢复一下awa

如果只是用于复制的话，已经准备开放了
https://github.com/cinit/QNotified/pull/279

**Comment by singleNeuron** [comment]
今天的CI版本已经开放
