### ISSUE TITLE
[Feature]为特殊功能增加30s-1.5m不等时常的教育小短片-没妈妈的人特供

### ISSUE THREAD

**Issue by huajijam** [cinit/QNotified#287]
没妈妈的人特供
每次使用该功能强制收看，声音等自动拉满+软件判断，教育小短片时间若点关闭则自动播放1-2m的广告(顺便恰点零食费),看完不跳广告

**Comment by singleNeuron** [comment]
@huajijam 在写了在写了

**Comment by huajijam** [comment]
> @huajijam 在写了在写了

发完秒回草

**Comment by huajijam** [comment]
//EULA 
//我已阅读并同意用户协议blob:https://web.telegram.org/bee5e178-1d3f-487e-bc29-46b92b92d8fa

**Comment by cxzlw** [comment]
所以最后加了吗

**Comment by taycke** [comment]
@cxzlw 没有

**Comment by cxzlw** [comment]
> @cxzlw 没有

。。。

**Comment by systemoutprintlnhelloworld** [comment]
可惜了
