### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by yuhangrao** [cinit/QNotified#300]
请问是还在维护吗，这个CI构建下载是以后的发布平台了吗，readme说有风险，但是模块已经显示尽快下载更新了。
![Screenshot_20200910-075437](https://user-images.githubusercontent.com/28585220/92666217-38d00b80-f33b-11ea-90fc-c27dbe0e596a.png)

**Comment by cinit** [comment]
@yuhangrao 开发环境就是生产环境，生产环境就是开发环境，测试版就是正式版

**Comment by yuhangrao** [comment]
> @yuhangrao 开发环境就是生产环境，生产环境就是开发环境，测试版就是正式版

好的谢谢！
