### ISSUE TITLE
点击历史好友黑屏

### ISSUE THREAD

**Issue by luckyzyx** [cinit/QNotified#310]
点击QN的历史好友跳转到一个黑屏页面，然后QQ卡死，只能返回桌面强制结束QQ

**Comment by cinit** [comment]
@luckyzyx 太极?

**Comment by luckyzyx** [comment]
> @luckyzyx 太极?

太极阴

**Comment by singleNeuron** [comment]
@luckyzyx 华为加太极，智慧无人极

**Comment by luckyzyx** [comment]
好像是点击历史好友直接闪退了，但太极给拦截阻止QQ闪退，所以只显示黑屏

**Comment by luckyzyx** [comment]
> @luckyzyx 那就别用太极

那我用啥？你又不能让官方给我提前解锁

**Comment by huajijam** [comment]
@luckyzyx 用vxp VMOS 请

**Comment by singleNeuron** [comment]
@luckyzyx 用苹果

人品不高智商低，慎用安卓智能机

**Comment by luckyzyx** [comment]
反馈个问题倒成了被劝退，真不错

**Comment by huajijam** [comment]
@luckyzyx 建议和taichi作者讨论这个问题，他肯解决我们就解决

**Comment by luckyzyx** [comment]
> @luckyzyx 建议和taichi作者讨论这个问题，他肯解决我们就解决

我都不知道为啥闪退，又怎么和taichi讨论呢？

**Comment by singleNeuron** [comment]
@luckyzyx 你问太极去，阻止闪退是太极的功能又不是我们的
