### ISSUE TITLE
QQ8.2.7 简洁模式圆形头像失效

### ISSUE THREAD

**Issue by CirnoSalt** [cinit/QNotified#35]

**Comment by cinit** [comment]
模块(目前)和太极存在的兼容性问题...下(下)个版本尝试修复...其实你把太极换riru+edxp就能解决问题了

**Comment by cinit** [comment]
是简洁模式暗色主题下失效还是全部失效?

**Comment by CirnoSalt** [comment]
全部失效，已尝试重置模块和清除缓存无效，并且QQ进程出现偶尔fc情况。

**Comment by inkhog** [comment]
我用还可以圆头，华为MATE10的Android10

**Comment by singleNeuron** [comment]
试试新版有没有解决（支持835及以上）
827已不再维护
