### ISSUE TITLE
建议：TIM接收到小程序分享转化为普通分享

### ISSUE THREAD

**Issue by mnixry** [cinit/QNotified#38]
TIM现在接收到小程序分享打不开
但是b站和知乎都已经开始采用小程序
有没有办法转换成普通分享

或者不求通解只求一些流行app的转换也可以
如果这样建议可以开放规则编辑的接口供社区添加自定义的应用规则

**Comment by cinit** [comment]
Emmm...有点难搞

**Comment by luoquan-30** [comment]
新版已经支持小程序了哦

**Comment by mnixry** [comment]
TIM内测版2.5.8已支持小程序分享
经过本人分析该功能在技术上实现难度较大
本issue关闭
引申新issue：在TIM内测版上的支持跟进 #58

**Comment by singleNeuron** [comment]
https://github.com/ferredoxin/QNotified/pull/660
