### ISSUE TITLE
Bug：几个细节问题

### ISSUE THREAD

**Issue by mnixry** [cinit/QNotified#39]
>  手机型号：MI 6X
>  系统：Havoc 3.1（Android 10）
>  Xposed版本：Edxposed-0.4.6.1-Sandhook
>  QQ版本：8.2.7
>  QN版本：0.6.0-rc2

1. `自定义电量` 值取0不生效，建议设置为只能取正整数
2. `简洁模式圆头像` 的开启会导致简洁模式无法正常开关，且开启后对动态页的简洁失效（原来点动态页直接进空间）

**Comment by cinit** [comment]
设置0会变成1 ?   还是显示别的?

**Comment by mnixry** [comment]
> 设置0会变成1 ? 还是显示别的?

是设置0的时候没有效果，我的建议是把程序对电量的限制改为`[1,100]`

**Comment by singleNeuron** [comment]
电量已有提示，新版简洁模式圆头像已修复此问题
