### ISSUE TITLE
希望加入保存闪照功能

### ISSUE THREAD

**Issue by zhsmark** [cinit/QNotified#44]
一人血书加入保存闪照功能

**Comment by zhsmark** [comment]
我开了但是还是不能看闪照。。。我的问题，一加7pro 无极

**Comment by cinit** [comment]
QQ版本8.2.7.4410吗?
升级到8.2.8试试

**Comment by 793145170** [comment]
8.2.8闪照破解失效 QN0.6.0-rc2

**Comment by zhsmark** [comment]
> QQ版本8.2.7.4410吗?
> 升级到8.2.8试试

恩恩，没问题了
