### ISSUE TITLE
自定义电量的版本内外描述不符

### ISSUE THREAD

**Issue by wqk317** [cinit/QNotified#45]
外边是8.2.6，点开是6.2.8。。。

**Comment by GitYohoo** [comment]
自定义电量也无效，只能自己看是修改后的

**Comment by cinit** [comment]
更新0.7.1-beta后正常了吧?

**Comment by wqk317** [comment]
我这边好使了🤔(甚至8.3.0测试版都好使)
不过里外的提示还是不一致😂

**Comment by cinit** [comment]
里外不一致是个啥

**Comment by wqk317** [comment]
> 里外不一致是个啥

哈哈哈，就是那个功能描述啦，
外边提示[ QQ>=8.2.6]在线模式为我的电量时生效
点开里边是“！！！此功能仅在QQ＞＝6.2.8xxxxxx”😂
估计是手滑打错了吧

**Comment by cinit** [comment]
忘记改了...
