### ISSUE TITLE
建议把动态页面是否直接进入QQ空间作为一个可选开关

### ISSUE THREAD

**Issue by Turroise** [cinit/QNotified#48]
QQ现在的版本下点击动态页面会直接进入QQ空间 但是激活模块后点击这一页面就不会进入空间而是之前的二级菜单

**Comment by cinit** [comment]
这个是不是和简洁模式有关啊

**Comment by wqk317** [comment]
这个好像确实很迷，点动态tab，一会直接进空间，一会还有二级菜单，没搞清楚是什么逻辑

**Comment by ccjjxx99** [comment]
开了简洁模式就会自动进入空间，如果打开简洁模式圆头像，就会有二级菜单，而且运动，游戏之类的也会出现。所以应该是圆头像这个功能不止修改了头像，还把动态页面修改为了非简洁模式

**Comment by Turroise** [comment]
> 开了简洁模式就会自动进入空间，如果打开简洁模式圆头像，就会有二级菜单，而且运动，游戏之类的也会出现。所以应该是圆头像这个功能不止修改了头像，还把动态页面修改为了非简洁模式

原来是这样！涨知识了 谢谢您的解答

**Comment by Turroise** [comment]
> 这个是不是和简洁模式有关啊

是的 看下面的replay

**Comment by Turroise** [comment]
> 开了简洁模式就会自动进入空间，如果打开简洁模式圆头像，就会有二级菜单，而且运动，游戏之类的也会出现。所以应该是圆头像这个功能不止修改了头像，还把动态页面修改为了非简洁模式

是武大校友吗哈哈哈

**Comment by ccjjxx99** [comment]
> > 开了简洁模式就会自动进入空间，如果打开简洁模式圆头像，就会有二级菜单，而且运动，游戏之类的也会出现。所以应该是圆头像这个功能不止修改了头像，还把动态页面修改为了非简洁模式
> 
> 是武大校友吗哈哈哈

卧槽这么巧吗

**Comment by singleNeuron** [comment]
试试新版简洁模式圆头像
