### ISSUE TITLE
功能小期望

### ISSUE THREAD

**Issue by zhsmark** [cinit/QNotified#49]
希望大佬增加消息撤回后的提醒，不然不知道哪条消息撤回了。。。。

**Comment by kumoilain** [comment]
安卓10、magisk-20.3、riru-c19.7、edxp-0.461-egicwlug、QQ-8.1.8，可以显示撤回文字内容
![QQ图片20200308145716](https://user-images.githubusercontent.com/29969516/76158105-1fac8f00-614d-11ea-9884-504dca23687a.jpg)

**Comment by cccccpppppp** [comment]
MIUI11，红米k30 5g  QQ8.2.8同不可显示撤回内容

**Comment by cinit** [comment]
更新0.7.1-beta后有了吗?

**Comment by cccccpppppp** [comment]
> 更新0.7.1-beta后有了吗?

@cinit 经测试更新后已经有提示了
![image](https://user-images.githubusercontent.com/24277775/76974264-f3beb400-696b-11ea-9b46-f486b19a5181.png)
