### ISSUE TITLE
[feature request]使简洁模式下的头像显示为圆形

### ISSUE THREAD

**Issue by batkiz** [cinit/QNotified#5]

**Comment by cinit** [comment]
难搞哦...#(cry)

**Comment by HinataKato** [comment]
> It seems hard...
> 我都没用过简洁模式

ColorQQ这个模块在简洁模式下头像会变成圆形的（

**Comment by batkiz** [comment]
> > It seems hard...
> > 我都没用过简洁模式
> 
> ColorQQ这个模块在简洁模式下头像会变成圆形的（

thx, 我去试试（
