### ISSUE TITLE
[Bug]QQ8.2.8 我的电脑发送的文件下载失败

### ISSUE THREAD

**Issue by yuhangrao** [cinit/QNotified#50]
经过反复测试，清空QQ数据后恢复正常，一使用模块就重现，禁用模块后恢复正常。下载电脑发送到手机的文件会下载失败或者一直不动，群聊或者个人没有问题

**Comment by cinit** [comment]
QQ版本多少?

**Comment by by-love** [comment]
> QQ版本多少?

8.28

**Comment by huajijam** [comment]
因过于久远且无法求证是否修复(QQ版本<8.3.x或发送日期早于4.1)而关闭，若未BUG修复请重投issues
