### ISSUE TITLE
强制默认字体

### ISSUE THREAD

**Issue by Vstory** [cinit/QNotified#51]
看到QN设置项里增加了**强制默认气泡**，能否支持强制所有字体为**默认字体**。
不是太喜欢简洁模式，但是一部分用户就喜欢**霸气超大字**等个性字体（看到一个屏蔽一个），太多，我真的屏蔽累了。

ps:不是说讨厌字体，而是少部分群体，花里胡哨的：
- 1.根本看不清字（字体太细，草体以及其他难以辨认的个性字体）；
- 2.气泡花里胡哨的，看气泡里的文字，还得等气泡动画展示完；
  - 2.1. 气泡动画展示完后，再给你来个看不清、难以辨认字的个性字体。

**Comment by wqk317** [comment]
哈哈哈，点个赞，这个确实可以有，简洁模式用户默默飘过

**Comment by Vstory** [comment]
> 哈哈哈，点个赞，这个确实可以有，简洁模式用户默默飘过


这部分**天选之子**，屏蔽不尽。
