### ISSUE TITLE
[Bug]QQ8.2.6-8.2.7 自定义骰子无法正常显示/使用

### ISSUE THREAD

**Issue by SinanGentoo** [cinit/QNotified#54]
在使用自定义骰子功能时骰子大概率会卡住或无法加载，关闭自定义骰子后正常。
出现该问题的QQ版本：8.2.6-8.2.7
出现该问题的QN版本：0.5.2-0.7.1

**Comment by wqk317** [comment]
我好像没遇到, 8.2.7/8.2.8/8.3.0都没问题, 抓个log给作者看看吧

**Comment by huajijam** [comment]
因过于久远且无法求证是否修复(QQ版本<8.3.x或发送日期早于4.1)而关闭，若未BUG修复请重投issues
