### ISSUE TITLE
使用QN后无法举报，按钮缩小

### ISSUE THREAD

**Issue by SinanGentoo** [cinit/QNotified#55]
如图，举报提示群名片启动失败

![Screenshot_20200319-115000_QQ.png](https://i.loli.net/2020/03/19/XlKvcVorB4weZTY.png)

**Comment by SinanGentoo** [comment]
已排除substratum主题问题

**Comment by huajijam** [comment]
因过于久远且无法求证是否修复(QQ版本<8.3.x或发送日期早于4.1)而关闭，若未BUG修复请重投issues
