### ISSUE TITLE
能否开放一个测试通道啥的，例如每更新一次工作流就编译一下…

### ISSUE THREAD

**Issue by Neubulae** [cinit/QNotified#63]
尝鲜啥的（（

**Comment by cinit** [comment]
这个问题git pull后自行编译就能解决(其实是我懒)

**Comment by Neubulae** [comment]
> 这个问题git pull后自行编译就能解决(其实是我懒)

那用的什么编译的啊

**Comment by wutong233** [comment]
> 这个问题git pull后自行编译就能解决(其实是我懒)

大佬，要不你出个简易编译教程什么的？那样就不用催了你也可以懒了（手动滑稽

**Comment by BlueJett** [comment]
> 这个问题git pull后自行编译就能解决(其实是我懒)

可以尝试用一下Github自带的Actions（
