### ISSUE TITLE
[Bug]QQ8.1.5 以图片打开表情功能偶尔失灵

### ISSUE THREAD

**Issue by HinataKato** [cinit/QNotified#7]
QQ版本为8.1.5 MIUI11 AndroidQ Edxposed
失灵后需要手动关闭再打开

**Comment by cinit** [comment]
请问 "手动关闭再打开" 要杀死并重新打开QQ吗?

**Comment by HinataKato** [comment]
> 请问 "手动关闭再打开" 要杀死并重新打开QQ吗?

不需要 这东西概率完全就是碰运气

**Comment by HinataKato** [comment]
@cinit 我又遇到了一次 但是我重新点开了几次就好了…

**Comment by cinit** [comment]
有没有log?
你重新点开关的时候，qn会发起重加载请求(而且是跨进程的)...
我想看一下到底怎么回事

**Comment by HinataKato** [comment]
> 有没有log?
> 你重新点开关的时候，qn会发起重加载请求(而且是跨进程的)...
> 我想看一下到底怎么回事

我注意一下吧 刚才又遇到了一次… 也是重新点几次就好了…

**Comment by HinataKato** [comment]
@cinit 貌似触发这个bug的办法是在高版本回复表情 我刚想抓log它就恢复了…

**Comment by HinataKato** [comment]
https://paste.ubuntu.com/p/6SJbWZ9gv7/
log在这里

**Comment by cinit** [comment]
@HinataKato 要Xposed的日志...不是Android日志...

**Comment by HinataKato** [comment]
> @HinataKato 要Xposed的日志...不是Android日志...

Edxposed看不了… 一看就卡死 你自己照我说的触发条件试试吧

**Comment by huajijam** [comment]
因过于久远且无法求证是否修复(QQ版本<8.3.x或发送日期早于4.1)而关闭，若未BUG修复请重投issues
