### ISSUE TITLE
QQ 8.3.3闪照失效以及混淆类每次启动都需要重定位

### ISSUE THREAD

**Issue by L245T** [cinit/QNotified#71]
1. qq8.3.3破解闪照失效
2. qq掉内存的情况下每次重新打开qq必现重新定位被混淆类com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory

## 环境：
Redmi k20 pro 
miui 11 20.3.7 基于安卓10
太极6.0.2
magisk 20.3

## 故障排查处截图
![故障排查处截图1](https://github.com/L245T/images/raw/master/issures/2020/qnotified/Screenshot_2020-04-16-09-15-34-849_com.tencent.mobileqq.jpg)
![故障排查处截图2](https://github.com/L245T/images/raw/master/issures/2020/qnotified/Screenshot_2020-04-16-09-15-39-052_com.tencent.mobileqq.jpg)

**Comment by zyx2813467705** [comment]
最新版本启动的混淆类问题和闪照

**Comment by greenhat616** [comment]
同样存在这个问题

**Comment by ibanxia** [comment]
同样是此类问题。
QQ版本：8.3.3
闪照失效
启动登录定位的问题
求大佬更新一下

**Comment by L245T** [comment]
根据作者的 [新的commit](https://github.com/cinit/QNotified/commit/57861d265cd313083c0adf0d7ffa878d4efabb80) 
关闭下面两个功能
1. 【图片方式打开闪照】
2. 【签到文本化】
即可跳过QQ启动时的反混淆界面
但是破闪照功能以及签到文本化功能暂时无法使用，目前关闭这两个可以作为目前当前版本的过渡日用，这两个功能的修复还要等到作者修复更新

**Comment by ibanxia** [comment]
好的谢谢

**Comment by mrzhang-264** [comment]
thanks
