### ISSUE TITLE
能不能在模块关于或者哪里加个支持版本

### ISSUE THREAD

**Issue by Kaifeng666** [cinit/QNotified#75]
希望能有个地方能看见现在完美支持到哪个版本
更新公告里说适配更多太模糊了
还有就是有没有交流群 QQ or telegram频道？

**Comment by singleNeuron** [comment]
咕咕华自称6.5.5以上全部支持，实际使用过程中最近的几个版本都不会有太大问题
Telegram：https://t.me/QNotified
