### ISSUE TITLE
Gradle相关文件缺失，程序无法编译

### ISSUE THREAD

**Issue by mnixry** [cinit/QNotified#79]
缺失gradle相关文件，无法进行编译
*.gradle在.gitignore里面

相关issue： #63

**Comment by ccoccc** [comment]
自己补一下不就好了

**Comment by Creedowl** [comment]
gradle里面包含一些配置信息，自己不好补吧

**Comment by ccoccc** [comment]
不难，也不用配置啥，compileOnly一下XposedBridgeApi，然后就是怎么处理stub目录的问题，stub这个目录也是需要不参与编译的
