### ISSUE TITLE
【TIM】防撤回的消息底下不显示“**撤回了一条消息”

### ISSUE THREAD

**Issue by Decwar** [cinit/QNotified#8]
【TIM】防撤回的消息底下不显示“**撤回了一条消息”，无法知道哪条消息是被撤回的
TIM  v2.3.1
qnotified v0.4.1
xposed

**Comment by cinit** [comment]
不只是TIM2.3.1,在QQ上也是如此.
弱弱问一句TIM2.3.1哪里下的?我只有TIM2.3.0

**Comment by Decwar** [comment]
> 不只是TIM2.3.1,在QQ上也是如此.
> 弱弱问一句TIM2.3.1哪里下的?我只有TIM2.3.0

酷安上好像有2.3.1版本
