### ISSUE TITLE
反馈0.8.0的一个bug

### ISSUE THREAD

**Issue by litianyuhehe** [cinit/QNotified#86]
就是从简洁模式切换到其他模式以后，无法在切换回简洁模式了，会卡住

**Comment by JasonKhew96** [comment]
QQ 8.3.6 EdXposed 无法复现
请检查是不是和其他模块冲突了

**Comment by litianyuhehe** [comment]
只开了一个，其他都关了，设置里也只能看到一个

**Comment by litianyuhehe** [comment]
又测了下，好像跟简洁模式圆头像有关

**Comment by litianyuhehe** [comment]
开圆头像从默认切简洁会卡住，关掉后从简洁切默认会卡住
