### ISSUE TITLE
仅以化学筛选是否过于死板，以及操作问题

### ISSUE THREAD

**Issue by wutong233** [cinit/QNotified#88]
高中没选化学科目怎么搞啊...求个物理/生物计算？
还有在选择手性碳原子时点击无*出现和点击*不消失的现象时有发生，望改善

**Comment by zyk1994** [comment]
同,工作好几年了,看到这个验证属实崩溃...都忘干净了

**Comment by Yachfu** [comment]
没学过化学，手性碳原子百度半天都没看懂是个啥，允悲

**Comment by 4a756e6f** [comment]
https://www.bilibili.com/video/av583311157/
看完这个 再刷个简单的就轻松了

**Comment by dangehub** [comment]
其实挺简单的，必须是饱和C,而且四个基团要不同

**Comment by CCCClass** [comment]
通过这个验证之后有啥用呢？多了功能吗？我怎么看不到。。。。

**Comment by greenhat616** [comment]
> 其实挺简单的，必须是饱和C,而且四个基团要不同

其实最主要的问题还是选修问题。比如说江苏现有的常规选修是物理，生物。放在全国范围也一样，如果选的是文科一般不选化学；理科也有物生地的选择。私认为直接用理综库、文综库等题库或许更合理一些

**Comment by xxq04** [comment]
看看也能会

**Comment by greenhat616** [comment]
：（ 我有这时间为什么不选择能实现价值的工作、能提升价值的学习，亦或是减轻压力的游戏呢？
进入了社会，就会囿于自己的圈子。或许学习这门技艺能收获快乐，但对于我们这些尚未深研这门学科的人来说，只是件费力不讨好的工作。


以上，我的看法。



---原始邮件---
发件人: "xxq04"<notifications@github.com&gt;
发送时间: 2020年8月4日(周二) 晚上7:21
收件人: "cinit/QNotified"<QNotified@noreply.github.com&gt;;
抄送: "Jonson Petard"<i@a632079.me&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [cinit/QNotified] 仅以化学筛选是否过于死板，以及操作问题 (#88)




 
看看也能会

**Comment by xxq04** [comment]
> > 其实挺简单的，必须是饱和C,而且四个基团要不同
> 
> 其实最主要的问题还是选修问题。比如说江苏现有的常规选修是物理，生物。放在全国范围也一样，如果选的是文科一般不选化学；理科也有物生地的选择。私认为直接用理综库、文综库等题库或许更合理一些

emm我也认为这样有点不妥，我也是刷新了好多好多次，终于刷新个简单点的，然后才勉强做出来

**Comment by xxq04** [comment]
> > 其实挺简单的，必须是饱和C,而且四个基团要不同
> 
> 其实最主要的问题还是选修问题。比如说江苏现有的常规选修是物理，生物。放在全国范围也一样，如果选的是文科一般不选化学；理科也有物生地的选择。私认为直接用理综库、文综库等题库或许更合理一些

最好加个选科功能

**Comment by cinit** [comment]
那换求导? 求导文理都学

**Comment by is-ibuprofen** [comment]
建议换成完形填空

**Comment by wutong233** [comment]
> 那换求导? 求导文理都学

那吼啊，虽然我没学（滑稽
现在找手性碳原子都有极度简单的固定方法了:找个正方形，左上左下右下和右上远一点选中就过...

**Comment by xxq04** [comment]
> > 那换求导? 求导文理都学
> 
> 那吼啊，虽然我没学（滑稽
> 现在找手性碳原子都有极度简单的固定方法了:找个正方形，左上左下右下和右上远一点选中就过...

我还是觉得手性碳简单点。。。

**Comment by cinit** [comment]
已经没有验证了
