### ISSUE TITLE
增加去除群消息右上角小程序图标

### ISSUE THREAD

**Issue by HinataKato** [cinit/QNotified#9]
![IMG_20191122_010741_Mosaic_1_7_46](https://user-images.githubusercontent.com/57648531/69360011-b8b1ba00-0cc4-11ea-8d16-3c5c6b9433cc.jpg)
如题 图标是从左往右第二个

**Comment by cinit** [comment]
是群友爱玩(游戏中心)吗？

**Comment by HinataKato** [comment]
> 是群友爱玩(游戏中心)吗？

是

**Comment by cinit** [comment]
8.2.0变成一起嗨了
