### ISSUE TITLE
反馈个问题以及一个吐槽

### ISSUE THREAD

**Issue by ElementBridge** [cinit/QNotified#91]
问题:简洁模式圆头像夜间模式下好像还是方形的。好几个版本都是这样

吐槽:那个问题只有手性碳原子，Ó╭╮Ò可我高中学的是晶胞结构。太难了我

**Comment by cinit** [comment]
简洁模式圆头像原理其实是欺骗客户端让它误以为是普通模式, 然后头像就圆了...(用了会有各种各样奇怪的问题)... 至于验证, 不用qun发的话根本没必要去验证

**Comment by leohearts** [comment]
开了这个功能后我再也切换不到普通模式了, 只能清除数据(

**Comment by singleNeuron** [comment]
新版简洁模式圆头像应该修复了大部分问题
